name: Deploy to AWS S3
descritpion: Deploy to a static website using Amazon S3
inputs:
  bucket:
    description: The S3 bucket name
    required: true
  bucket-region:
    description: The region of the S3 region
    required: false
    default: us-east-1
  dist-folder:
    description: The folder containing the deployable files
    required: true

outputs:
  output-value:
    description: The value to be output by the action

runs:
  using: docker
  image: Dockerfile