name: 'Get & Cache Dependencies'
descripton: 'Get the dependencies (via NPM) and cache them'
inputs:
  disable-cacheing:
    description: Disables the cacheing step, ensuring dependencies are ALWAYS installed
    required: false
    default: 'false'

outputs:
  cache-used:
    description: Specifies whether the cache was used
    value: ${{ steps.install.outputs.cache }}

runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.disable-cacheing != 'true'
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.disable-cacheing == 'true'
      run: |
        npm ci
        echo "cache='fred'" >> $GITHUB_OUTPUT
      shell: bash